const CACHE = 'my-love-is-you-v20-chest-replay-miniplayer';
const CORE = ['/', '/index.html', '/styles.css', '/config.js', '/src/app.js', '/src/nana.js', '/src/store.js', '/src/animations.js', '/src/cinema.js', '/cinema.css', '/animations.css', '/assets/logo.webp', '/assets/heart-main.webp', '/assets/avatar-adriel.webp', '/assets/avatar-maria.webp', '/assets/pet-cat.webp', '/assets/couple-polaroids.webp', '/assets/proposal/banner.webp', '/assets/proposal/sim-heart.webp', '/assets/proposal/nana-ring.webp', '/assets/proposal/ring-box.webp', '/assets/proposal/envelope.webp', '/manifest.webmanifest', '/assets/app-icons/icon-192.png', '/assets/app-icons/icon-512.png', '/themes.css', '/src/themes.js', '/assets/themes/hunter/map.webp', '/assets/themes/hunter/crystals.webp', '/assets/themes/hunter/target.webp', '/assets/themes/hunter/backpack.webp', '/assets/themes/hunter/green-tent.webp', '/assets/themes/hunter/compass.webp', '/assets/themes/hunter/license.webp', '/assets/themes/hunter/yoyo.webp', '/assets/themes/hunter/blue-potion.webp', '/assets/themes/bleach/talismans.webp', '/assets/themes/bleach/skull-crest.webp', '/assets/themes/bleach/torii-portal.webp', '/assets/themes/bleach/butterfly.webp', '/assets/themes/bleach/lantern.webp', '/assets/themes/bleach/orb.webp', '/assets/themes/bleach/skull-charm.webp', '/assets/themes/bleach/flame.webp', '/assets/themes/bleach/energy-slash.webp', '/assets/themes/fullmetal/alchemy-circle-blue.webp', '/assets/themes/fullmetal/chest.webp', '/assets/themes/fullmetal/red-crystal.webp', '/assets/themes/fullmetal/pocket-watch.webp', '/assets/themes/fullmetal/brown-book.webp', '/assets/themes/fullmetal/coin.webp', '/assets/themes/fullmetal/alchemy-book.webp', '/assets/themes/fullmetal/alchemy-circle-red.webp', '/assets/themes/fullmetal/potion.webp', '/assets/themes/fullmetal/sketch.webp', '/assets/themes/one-piece/map.webp', '/assets/themes/one-piece/chest.webp', '/assets/themes/one-piece/island.webp', '/assets/themes/one-piece/straw-hat.webp', '/assets/themes/one-piece/wheel.webp', '/assets/themes/one-piece/compass.webp', '/assets/themes/one-piece/message-bottle.webp', '/assets/themes/one-piece/anchor.webp', '/assets/themes/one-piece/gems-large.webp', '/assets/themes/blue-lock/tactics-board.webp', '/assets/themes/blue-lock/scoreboard.webp', '/assets/themes/blue-lock/goal-text.webp', '/assets/themes/blue-lock/ball.webp', '/assets/themes/blue-lock/target.webp', '/assets/themes/blue-lock/whistle.webp', '/assets/themes/blue-lock/energy-burst.webp', '/assets/themes/blue-lock/energy-slash.webp', '/assets/themes/blue-lock/corner-flag.webp', '/theme-hotfix.css', '/src/theme-hotfix.js', '/couple-tools.css', '/src/couple-tools.js', '/profile-theme.css', '/romance-polish.css', '/src/profile-theme.js', '/src/install-love.js', '/relationship-extras.css', '/src/relationship-extras.js', '/v20-fixes.css', '/src/v20-fixes.js'];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(CORE)).then(() => self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  event.respondWith(fetch(event.request).then(response => {
    const copy = response.clone(); caches.open(CACHE).then(cache => cache.put(event.request, copy)); return response;
  }).catch(() => caches.match(event.request).then(hit => hit || caches.match('/index.html'))));
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
